# Generated by Django 3.2.6 on 2021-08-04 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='deleted_at',
        ),
    ]
