# Generated by Django 3.2.6 on 2021-09-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20210918_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
