# Generated by Django 3.2.6 on 2021-11-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20210918_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_promo',
            field=models.DateTimeField(blank=True, default='2021-09-19 00:36:08.101176-03', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
