# Generated by Django 3.2.6 on 2021-08-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_anuncio_slug2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='slug2',
        ),
    ]
