# Generated by Django 3.2.6 on 2021-08-10 17:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_remove_anuncio_slug2'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='slug2',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='modelo', unique=True),
            preserve_default=False,
        ),
    ]
