# Generated by Django 3.2.6 on 2021-08-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_alter_anuncio_id_usr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
