# Generated by Django 3.2.6 on 2021-08-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0007_anunciofoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='image_capa',
            field=models.ImageField(blank=True, upload_to='img_capa/%Y/%m/', verbose_name='Foto Principal do Anúncio'),
        ),
        migrations.AlterField(
            model_name='anunciofoto',
            name='image',
            field=models.ImageField(upload_to='img_anuncios/%Y/%m/', verbose_name='Foto do Veículo'),
        ),
    ]
