# Generated by Django 3.2.6 on 2021-08-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0008_auto_20210825_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='image_capa',
            new_name='image',
        ),
    ]
