# Generated by Django 3.2.6 on 2021-08-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0009_rename_image_capa_anuncio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='marca',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
