# Generated by Django 3.2.6 on 2021-09-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0010_alter_anuncio_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='ano',
            field=models.IntegerField(blank=True, choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='marca_id',
            field=models.IntegerField(choices=[('4', 'AM Gen'), ('189', 'ASTON MARTIN'), ('1', 'Acura'), ('2', 'Agrale'), ('3', 'Alfa Romeo'), ('5', 'Asia Motors'), ('6', 'Audi'), ('7', 'BMW'), ('8', 'BRM'), ('207', 'Baby'), ('123', 'Bugre'), ('236', 'CAB Motors'), ('11', 'CBT Jipe'), ('136', 'CHANA'), ('182', 'CHANGAN'), ('10', 'Cadillac'), ('161', 'Caoa Chery'), ('12', 'Chrysler'), ('13', 'Citroën'), ('14', 'Cross Lander'), ('15', 'Daewoo'), ('16', 'Daihatsu'), ('17', 'Dodge'), ('147', 'EFFA'), ('18', 'Engesa'), ('19', 'Envemo'), ('190', 'FOTON'), ('20', 'Ferrari'), ('21', 'Fiat'), ('149', 'Fibravan'), ('22', 'Ford'), ('170', 'Fyber'), ('199', 'GEELY'), ('23', 'GM - Chevrolet'), ('153', 'GREAT WALL'), ('24', 'Gurgel'), ('152', 'HAFEI'), ('214', 'HITECH ELECTRIC'), ('25', 'Honda'), ('26', 'Hyundai'), ('208', 'IVECO'), ('27', 'Isuzu'), ('177', 'JAC'), ('154', 'JINBEI'), ('30', 'JPX'), ('28', 'Jaguar'), ('29', 'Jeep'), ('31', 'Kia Motors'), ('171', 'LAMBORGHINI'), ('168', 'LIFAN'), ('127', 'LOBINI'), ('32', 'Lada'), ('33', 'Land Rover'), ('34', 'Lexus'), ('35', 'Lotus'), ('167', 'MG'), ('156', 'MINI'), ('140', 'Mahindra'), ('36', 'Maserati'), ('37', 'Matra'), ('38', 'Mazda'), ('211', 'Mclaren'), ('39', 'Mercedes-Benz'), ('40', 'Mercury'), ('41', 'Mitsubishi'), ('42', 'Miura'), ('43', 'Nissan'), ('44', 'Peugeot'), ('45', 'Plymouth'), ('46', 'Pontiac'), ('47', 'Porsche'), ('185', 'RAM'), ('186', 'RELY'), ('48', 'Renault'), ('195', 'Rolls-Royce'), ('49', 'Rover'), ('183', 'SHINERAY'), ('125', 'SSANGYONG'), ('50', 'Saab'), ('51', 'Saturn'), ('52', 'Seat'), ('54', 'Subaru'), ('55', 'Suzuki'), ('165', 'TAC'), ('56', 'Toyota'), ('57', 'Troller'), ('59', 'VW - VolksWagen'), ('58', 'Volvo'), ('163', 'Wake'), ('120', 'Walk'), ('157', 'smart')], null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='modelo',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
