# Generated by Django 3.2.6 on 2021-09-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0011_auto_20210907_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='cambio',
            field=models.CharField(blank=True, choices=[('Automático', 'Automático'), ('Manual', 'Manual')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='clique',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='combustivel',
            field=models.CharField(blank=True, choices=[('Gasolina', 'Gasolina'), ('Flex', 'Flex')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='gas',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='ipva_pago',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='marca_id',
            field=models.IntegerField(choices=[(4, 'AM Gen'), (189, 'ASTON MARTIN'), (1, 'Acura'), (2, 'Agrale'), (3, 'Alfa Romeo'), (5, 'Asia Motors'), (6, 'Audi'), (7, 'BMW'), (8, 'BRM'), (207, 'Baby'), (123, 'Bugre'), (236, 'CAB Motors'), (11, 'CBT Jipe'), (136, 'CHANA'), (182, 'CHANGAN'), (10, 'Cadillac'), (161, 'Caoa Chery'), (12, 'Chrysler'), (13, 'Citroën'), (14, 'Cross Lander'), (15, 'Daewoo'), (16, 'Daihatsu'), (17, 'Dodge'), (147, 'EFFA'), (18, 'Engesa'), (19, 'Envemo'), (190, 'FOTON'), (20, 'Ferrari'), (21, 'Fiat'), (149, 'Fibravan'), (22, 'Ford'), (170, 'Fyber'), (199, 'GEELY'), (23, 'GM - Chevrolet'), (153, 'GREAT WALL'), (24, 'Gurgel'), (152, 'HAFEI'), (214, 'HITECH ELECTRIC'), (25, 'Honda'), (26, 'Hyundai'), (208, 'IVECO'), (27, 'Isuzu'), (177, 'JAC'), (154, 'JINBEI'), (30, 'JPX'), (28, 'Jaguar'), (29, 'Jeep'), (31, 'Kia Motors'), (171, 'LAMBORGHINI'), (168, 'LIFAN'), (127, 'LOBINI'), (32, 'Lada'), (33, 'Land Rover'), (34, 'Lexus'), (35, 'Lotus'), (167, 'MG'), (156, 'MINI'), (140, 'Mahindra'), (36, 'Maserati'), (37, 'Matra'), (38, 'Mazda'), (211, 'Mclaren'), (39, 'Mercedes-Benz'), (40, 'Mercury'), (41, 'Mitsubishi'), (42, 'Miura'), (43, 'Nissan'), (44, 'Peugeot'), (45, 'Plymouth'), (46, 'Pontiac'), (47, 'Porsche'), (185, 'RAM'), (186, 'RELY'), (48, 'Renault'), (195, 'Rolls-Royce'), (49, 'Rover'), (183, 'SHINERAY'), (125, 'SSANGYONG'), (50, 'Saab'), (51, 'Saturn'), (52, 'Seat'), (54, 'Subaru'), (55, 'Suzuki'), (165, 'TAC'), (56, 'Toyota'), (57, 'Troller'), (59, 'VW - VolksWagen'), (58, 'Volvo'), (163, 'Wake'), (120, 'Walk'), (157, 'smart')], null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='seguro',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='status_anuncio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='status_excluir',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tipo',
            field=models.CharField(blank=True, default='Carro', max_length=20, null=True),
        ),
    ]
