# Generated by Django 3.2.6 on 2021-09-22 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0013_anuncio_cidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='anuncio_fim',
            field=models.DateTimeField(blank=True, default='2021-09-19 00:36:08.101176-03', null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='anuncio_inicio',
            field=models.DateTimeField(blank=True, default='2021-09-19 00:36:08.101176-03', null=True),
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('motorista_id', models.CharField(blank=True, max_length=255, null=True)),
                ('proprietario_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('anuncio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.anuncio')),
            ],
        ),
    ]
