# Generated by Django 3.2.6 on 2021-09-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0014_anuncio_conversa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('anuncio_id', models.CharField(blank=True, max_length=150, null=True)),
                ('motorista_id', models.CharField(blank=True, max_length=150, null=True)),
                ('proprietario_id', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('conversa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.conversa')),
            ],
        ),
    ]
