# Generated by Django 3.2.6 on 2021-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0016_anuncio_mensagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='motorista_nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='motorista_sobrenome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='proprietario_nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='proprietario_sobrenome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
