# Generated by Django 3.2.6 on 2021-09-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0017_anuncio_mensagens_nomes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='conversa_id',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='conversa',
            field=models.ForeignKey(default=76, on_delete=django.db.models.deletion.CASCADE, to='anuncios.conversa'),
            preserve_default=False,
        ),
    ]
