# Generated by Django 3.2.6 on 2021-09-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0019_anuncio_mensagens_idfk2'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='motorista_nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='conversa',
            name='motorista_sobrenome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='conversa',
            name='proprietario_nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='conversa',
            name='proprietario_sobrenome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
