# Generated by Django 3.2.6 on 2021-10-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0020_anuncio_conversa_nomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='criador',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
