# Generated by Django 3.2.6 on 2021-10-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0021_anuncio_mensagem_criador'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='motorista_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='conversa',
            name='proprietario_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='motorista_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='proprietario_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
