# Generated by Django 3.2.6 on 2021-10-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0022_anuncio_mensagem_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversa',
            name='motorista_username',
        ),
        migrations.RemoveField(
            model_name='conversa',
            name='proprietario_username',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='motorista_username',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='proprietario_username',
        ),
        migrations.AlterField(
            model_name='conversa',
            name='anuncio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversa', to='anuncios.anuncio'),
        ),
    ]
