# Generated by Django 3.2.6 on 2021-10-04 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0023_anuncio_mensagem_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='conversa_id',
            field=models.ForeignKey(default=80, on_delete=django.db.models.deletion.CASCADE, related_name='conversa_ref', to='anuncios.conversa'),
            preserve_default=False,
        ),
    ]
